services:
  nginx:
    container_name: nginx
    build: .
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    restart:
      - unless-stopped
    init: true
    stop_grace_period: 5s

  mariadb:
    container_name: mariadb
    build: .
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    restart: unless-stopped
    init: true
    stop_grace_period: 5s
  
  wordpress:
    container_name: wordpress
    build: .
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped
    init: true
    stop_grace_period: 5s

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jblaye/data/wordpress'
  mariadb:
    name: mariadb-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jblaye/data/mariadb'